# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.IntegerField()),
                ('file_name', models.FileField(upload_to='media')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Re upload', 'Re upload'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
